export const SPECIALTIES = [
  'Medicina General',
  'Medicina Interna',
  'Pediatría',
  'Ginecología y Obstetricia',
  'Cardiología',
  'Dermatología',
  'Endocrinología',
  'Gastroenterología',
  'Neurología',
  'Oftalmología',
  'Otorrinolaringología',
  'Psiquiatría',
  'Psicología Clínica',
  'Traumatología y Ortopedia',
  'Urología',
] as const

export const COUNTRIES = [
  'Ecuador',
  'Colombia',
  'Perú',
  'Chile',
  'Argentina',
  'México',
  'Estados Unidos',
  'España',
] as const

export const PROVINCIAS_ECUADOR = [
  'Azuay',
  'Bolívar',
  'Cañar',
  'Carchi',
  'Chimborazo',
  'Cotopaxi',
  'El Oro',
  'Esmeraldas',
  'Galápagos',
  'Guayas',
  'Imbabura',
  'Loja',
  'Los Ríos',
  'Manabí',
  'Morona Santiago',
  'Napo',
  'Orellana',
  'Pastaza',
  'Pichincha',
  'Santa Elena',
  'Santo Domingo de los Tsáchilas',
  'Sucumbíos',
  'Tungurahua',
  'Zamora Chinchipe',
] as const

export const ciudadesEcuador: Record<(typeof PROVINCIAS_ECUADOR)[number], string[]> = {
  Azuay: ['Cuenca', 'Gualaceo', 'Paute'],
  Bolívar: ['Guaranda', 'San Miguel'],
  Cañar: ['Azogues', 'La Troncal'],
  Carchi: ['Tulcán', 'San Gabriel'],
  Chimborazo: ['Riobamba', 'Guano'],
  Cotopaxi: ['Latacunga', 'La Maná'],
  'El Oro': ['Machala', 'Santa Rosa', 'Pasaje'],
  Esmeraldas: ['Esmeraldas', 'Atacames', 'Quinindé'],
  Galápagos: ['Puerto Ayora', 'Puerto Baquerizo Moreno'],
  Guayas: ['Guayaquil', 'Durán', 'Samborondón', 'Daule', 'Milagro'],
  Imbabura: ['Ibarra', 'Otavalo', 'Cotacachi'],
  Loja: ['Loja', 'Catamayo'],
  'Los Ríos': ['Babahoyo', 'Quevedo', 'Ventanas'],
  Manabí: ['Portoviejo', 'Manta', 'Chone', 'Jipijapa'],
  'Morona Santiago': ['Macas', 'Sucúa'],
  Napo: ['Tena', 'Archidona'],
  Orellana: ['Francisco de Orellana (El Coca)', 'Loreto'],
  Pastaza: ['Puyo', 'Mera'],
  Pichincha: ['Quito', 'Cayambe', 'Sangolquí'],
  'Santa Elena': ['Santa Elena', 'La Libertad', 'Salinas'],
  'Santo Domingo de los Tsáchilas': ['Santo Domingo'],
  Sucumbíos: ['Nueva Loja (Lago Agrio)', 'Shushufindi'],
  Tungurahua: ['Ambato', 'Baños de Agua Santa', 'Pelileo'],
  'Zamora Chinchipe': ['Zamora', 'Yantzaza'],
}
